### PR TITLE
Integrate CMake file

### PR DESCRIPTION
**Pull request by Ali-Nasrolahi**
# Brief description on changes

Root cmake created with initializing aliases.

configuration files placed in conf/cmake. some of makefile features which represented in conf/make are not compatible with cmake sysntax, therefore need a little bit polishing. (for instance configuring the platform in user.cmake )

Absolutely open to any changes or resolving any mistake :)

### CODE REVIEW

**Review by aregtech — APPROVED** [review]

**Comment by aregtech** [comment]
Thank you, @Ali-Nasrolahi !
It's a good start. Would be nice if you remove multiple new-lines at the end or middle of files. Comments / descriptions are always welcomed.

**Comment by Ali-Nasrolahi** [comment]
Definitely. will be fixed on next PR.

**Comment by biwiki** [comment]
Sorry for jumping in the middle!
If this new build system can work with earlier versions of cmake than 3.18.0 then it would be great that we can relax the rule on the minimum cmake version.

**Comment by Ali-Nasrolahi** [comment]
I don't assume any specific feature which needs exactly 3.18 version, though this is just for the sake of compatibility with my own local system.

**Comment by biwiki** [comment]
Thanks! So I am supposed that it is okay to update it to 3.16 as it is the one I have here:
https://github.com/aregtech/areg-sdk/pull/42

**Pull request merged**
